<?php

namespace BCG\ContactBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends EntityRepository
{
	public function getAgencies()
    {
        $agencies = $this->createQueryBuilder('a')
                    ->select('a, u')
                    ->leftJoin('a.users', 'u')
                    ->addOrderBy('a.name', 'ASC');
                    
        return $agencies->getQuery()
                        ->getResult();
    }
}
