BCGContactBundle_homepage:
    path:     /
    defaults: { _controller: BCGContactBundle:Page:index }

BCGContactBundle_agency_show:
    path:  /agency/{id}
    defaults: { _controller: BCGContactBundle:Agency:show }
    requirements:
        id: \d+

BCGContactBundle_agency_edit:
    path:  /agency/{id}/edit
    defaults: { _controller: BCGContactBundle:Agency:edit }
    requirements:
        id: \d+

BCGContactBundle_user_edit:
    path:  /user/{user_id}/edit
    defaults: { _controller: BCGContactBundle:User:edit }
    requirements:
        user_id: \d+
