BCGContactBundle_homepage:
    path:     /
    defaults: { _controller: BCGContactBundle:Page:index }

BCGContactBundle_agency_show:
    path:  /{id}
    defaults: { _controller: BCGContactBundle:Agency:show }
    requirements:
        id: \d+
